steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        gunicorn -b 0.0.0.0:8080 app:app

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY
