steps:
  # Install GLIBC 2.28 manually
  - name: "gcr.io/cloud-builders/curl"
    args:
      - "-s"
      - "-L"
      - "-o"
      - "/tmp/glibc-2.28.tar.gz"
      - "http://ftp.gnu.org/gnu/libc/glibc-2.28.tar.gz"

  - name: "gcr.io/cloud-builders/bash"
    args:
      - "-c"
      - |
        cd /tmp
        tar -xvzf glibc-2.28.tar.gz
        cd glibc-2.28
        mkdir build
        cd build
        ../configure --prefix=/opt/glibc-2.28
        make -j$(nproc)
        make install
        echo "/opt/glibc-2.28/lib" >> /etc/ld.so.conf.d/glibc-2.28.conf
        ldconfig

  # Install dependencies
  - name: "gcr.io/cloud-builders/apt"
    args: [
      "install", "-y",
      "chromium", "chromium-driver",
      "libnss3", "libx11-xcb1", "libxcomposite1",
      "libxrandr2", "libasound2",
      "libxdamage1", "libxfixes3", "libxi6",
      "libxrender1", "libatk1.0-0", "libcairo2",
      "libpango-1.0-0", "libpangocairo-1.0-0",
      "libcups2", "libxshmfence1", "libgbm1"
    ]

  # Install Playwright
  - name: "python"
    entrypoint: "python"
    args: ["-m", "playwright", "install", "--with-deps"]

  # Install Python dependencies
  - name: "python"
    entrypoint: "pip"
    args: ["install", "-r", "requirements.txt"]

  # Run Gunicorn
  - name: "python"
    entrypoint: "gunicorn"
    args: ["-b", "0.0.0.0:8080", "app:app"]

timeout: "600s"

options:
  logging: CLOUD_LOGGING_ONLY
