services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget ca-certificates fonts-liberation libappindicator3-1 libasound2 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils
      pip install -r requirements.txt
      python -m playwright install
    startCommand: gunicorn app:app
