services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install
    startCommand: gunicorn app:app
